version: 1
update_configs:
  - package_manager: "javascript"
    directory: "frontend/"
    update_schedule: "daily"
  - package_manager: "javascript"
    directory: "backend/"
    update_schedule: "daily"
